apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: ds-important
    id: ds-imortant
    uuid: 18426a0b-5f59-4e10-923f-c0e078e82462   	
  name: ds-important
  namespace: project-tiger
spec:
 #replicas: 1
  selector:
    matchLabels:
      app: ds-important
      id: ds-imortant
      uuid: 18426a0b-5f59-4e10-923f-c0e078e82462
  #strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ds-important
        id: ds-imortant
        uuid: 18426a0b-5f59-4e10-923f-c0e078e82462
    spec:
      containers:
      - image: httpd:2.4-alpine
        name: https
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
#status: {}
