apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - name: webhook-server.webhook-demo.svc
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: webhook-server
        namespace: webhook-demo
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVSllxa1pvMmNHR0d2R0RWZkZRRXk5NjZ4WWFRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSXhNVEV3TkRFMU1UazFPVm9YRFRJeE1USXdOREUxTVRrMU9Wb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXNSREtUMURLTUZGRWFXKzF1S0cvRW9UbkNtaWFwZjR4YzNmUApaWUdBVnJGTkNuM3ZHbWJzeWNWSXh5WGxGblozeWhJUmhhajFQbzNSOXYzaHFOZFowNVZHSGNEeFd5Vm8wMU56ClpXbU9jL240VHZSbDlvckh5Szd1ay9MeW5qemJmWW1SVTlFbkxNMXd2bUUyNlNrQlZDZEUwOUV4YWhhdWcwa1UKNXlrV0ZFVGhGNkYrTlFPSTBwb3RSUGpXSmRxSUpxQzBSMXRUSlQxdVd0ajNERUtmWjl1ZVR0K0ErMHZWR0xZWAp2VG8zcmQvLzBVMjJjQkZXbUVmdUUwQmdjdExRSG43ZzFJNDc2U2wvTFJ3WXJuT1lPVnpPN1BscTRvdGdHZ2UrClJzczVBb2RWOFlKbGJleUxyUFBRVnRsQ2VwTDlBRzAyYTk1NjJQbUVPMVRycENwaVlRSURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVV290dnZUSmR2K1BaUUdLaVZsR3ZQcDVxYk1zd0h3WURWUjBqQkJnd0ZvQVVXb3R2dlRKZAp2K1BaUUdLaVZsR3ZQcDVxYk1zd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFhb3dYU2FUTGx4d0gvNk5QTG5FOXh1cWw5bUpiellZRDJ0UjdaUmhMczBDa2REY2dRays4ZXFYWXR2b1YKUGk2SlVWT00wRUE1eEFQeVdKK3lTc0VOVlNQQWpmek9kWFRLeTdlSlJFYWY0Yzg5bHZVMWdqdkNGTXlEWVl3VAptUVd5K0ZodHZXbXpNSlJmSHBRVGZZQ0UvZ0NJemFZQ1lUMUd5cGIyZHBDQXQ4T3pTUFhGcStqaU5reXljL3hYCjhzNWNQeHBkRXFMTzlOZzNVWlNjUmcrQTFIVjExVmFZZ0Z0MHVmdkR2c1grQUcraE85WTd2YjFnUHFXeW50SjkKTDNEaHhRRzhBdGVXNERIZGJGcGtZVkIyeHN1eGNnNXhheEU3NVFtR3pnRmdOU2hiYnhZV2kwR3o1SjVkWGc2WQphZDlldWlVN0VsMVZOQlI5b2xvMkxiNFlUQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
