apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-11-20T11:22:38Z"
  labels:
    run: manual-schedule
  name: manual-schedule
  namespace: default
  resourceVersion: "4253"
  uid: 1a95dc10-791b-496d-b09f-94dfe6a7c3c4
spec:
  nodeName: kmaster
  containers:
  - image: httpd:2.4-alpine
    imagePullPolicy: IfNotPresent
    name: manual-schedule
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-hc7t6
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-hc7t6
    secret:
      defaultMode: 420
      secretName: default-token-hc7t6
status:
  phase: Pending
  qosClass: BestEffort
