apiVersion: v1
kind: Pod
metadata:
  name: prod-redis
  namespace: default
spec:
  containers:
  - image: redis:alpine
    imagePullPolicy: IfNotPresent
  name: prod-redis
  tolerations:
  - effect: NoSchedule
    key: env_type
    operator: Equal
    value: production
